# BIOE 658J Midterm 2 , November 7, 2023

Name:Zannate Malik


## Problem 1 (40 points):
1. Write a Python expression that multiplies two 1D-ndarrays to obtain the following matrix:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
16 & 17 & 18 & 19 & 20\\
21 & 22 & 23 & 24 & 25\\
\end{pmatrix}$$

2. Write a Python expression to create a 1D-ndarray that contains all even numbers between 0 and 100 (inclusive), and a separate Python expression to create a 1D-ndarray that contains all odd numbers between 0 and 100 (inclusive).

3. Write a Python function `matrix_operation(A, B)` that takes two 2D-ndarrays as input and performs the following operation:
$$C = A^TBA$$
where $A$ and $B$ are both 2D-ndarrays, and $C$ is the resulting 2D-ndarray.
4. Using the `linalg.solve` function from numpy, solve the following system of linear equations:
```
x + y - z = 0
7x + 7y + 10z = 128
x + z = 4
```
5. Using the `linalg.eig` function from numpy, find the eigenvalues and eigenvectors of the following matrix:
$$\begin{pmatrix}
5 & 2 & 1 \\
2 & 3 & 1 \\
1 & 1 & 2 \\
\end{pmatrix}$$



make sure to run:
```python
import numpy as np
```


***Please solve each question in a seperate kernel.***


***Always provide examples that demonstrate the results obtained from your code, either through printing or plotting.***


In [17]:
# 1
import numpy as np
array1 = np.arange(1,26)
array2 = np.ones(25)

matrix = array1 * array2
matrix = matrix.reshape(5,5)
print(matrix)



[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [20]:
# 2
import numpy as np
array1 = np.arange(1,26)
array2 = np.ones(25)

matrix = array1 * array2
matrix = matrix.reshape(5,5)
print(matrix)

import numpy as np
even = np.arange(0, 101, 2)
odd = np.arange (1, 101, 2)

print(even)
print(odd)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [23]:
# 3
import numpy as np
def matrix_operation(A,B):
    if A.shape[1] == B.shape[0]:
        transA = A.T
        x = np.dot(np.dot(transA, B),A)
        return x
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

y = matrix_operation(A,B)
print(y)

[[116 172]
 [170 252]]


In [24]:
# 4
import numpy as np
A = np.array([[1, 1, -1], [7, 7, 10], [1, 0, 1]])
B = np.array ([0, 128, 4])

x = np.linalg.solve(A,B)
print(x)

[-3.52941176 11.05882353  7.52941176]


In [12]:
# 5


## Problem 2 (30 points):
The following data shows the weekly sales for each product in a store for the past month. Your task is to analyze the data and find the top 5 selling products:

| Product | Week 1 | Week 2 | Week 3 | Week 4 |
|---------|--------|--------|--------|--------|
| A       | 100    | 150    | 200    | 175    |
| B       | 75     | 90     | 95     | 110    |
| C       | 200    | 175    | 225    | 250    |
| D       | 120    | 130    | 140    | 150    |
| E       | 80     | 85     | 90     | 95     |


Using the Pandas module, perform the following tasks:

1. Create a DataFrame to store the data.

2. Calculate the total sales for each product.

3. Find the top 5 selling products.

4. Sort the DataFrame by the total sales in descending order.

5. Save the sorted DataFrame to a CSV file named "sales_data_sorted.csv".






In [13]:
import pandas as pd
# 1: Create a DataFrame to store the data


# 2: total sales for each product


# 3: top 5 selling products


# 4: Sort the DataFrame in descending order


# 5: Save the sorted DataFrame to a CSV 


## Problem 3 (30 points):
You are asked to create a Python program that reads sales data from a CSV file, performs some calculations on the data using pandas, and then writes the results to a new CSV file. The program should be implemented using object-oriented programming principles.

The CSV file "sales_data.csv" contains the following columns:

* `Product`: the name of the product
* `Quarter`: the quarter of the year (Q1, Q2, Q3, or Q4)
* `Sales`: the number of units sold in that quarter

You should create a `SalesData` class that has the following attributes:

* `filename`: the name of the CSV file to read the data from

The SalesData class should have the following methods:

* `calculate_product_sales`: this method should calculate the total sales for each product and return the result as a pandas DataFrame.

* `calculate_quarterly_sales`: this method should calculate the total sales for each quarter and return the result as a pandas DataFrame.

* `calculate_product_quarterly_sales`: this method should calculate the total sales for each product in each quarter and return the result as a pandas DataFrame.

* `write_data`: this method should write the results of the calculations to a new CSV file named "sales_summary.csv".

The main program should create an instance of the `SalesData` class and call its methods to read the data, perform the calculations, and write the results to the output file.


In [14]:
import pandas as pd

